backend:
  name: github
  repo: gmorlov/docs-dev

media_folder: static/img/uploads
public_folder: /img/uploads

publish_mode: editorial_workflow

collections:
  - name: procedures
    label: Procedures
    folder: content/procedures
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Contacts", name: "contacts", widget: "list"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
  - name: "intro"
    label: "intro"
    folder: "content/intro"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "appendicies"
    label: "appendicies"
    folder: "content/appendicies"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
